services:
  db:
    image: postgres:16.2
    container_name: book_game_db
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - db_network

  api:
    build: book_game_api
    container_name: book_game_api
    restart: always
    ports:
      - "3000:3000"
    networks:
      - db_network
    depends_on:
      - db

  web:
    build: book_game
    container_name: book_game_web
    restart: always
    ports:
      - "9090:80"
    volumes:
      - audio_data:/usr/share/nginx/html/audio

  tts:
    image: synesthesiam/marytts:5.2
    container_name: tts
    restart: always
    command: --voice upmc-pierre-hsmm
    networks:
      - audio_network

  speech:
    build: book_game_tts
    container_name: book_game_tts
    depends_on:
      - db
      - tts
    networks:
      - db_network
      - audio_network
    volumes:
      - audio_data:/app/out

volumes:
  db_data:
  audio_data:

networks:
  db_network:
  audio_network:
