services:
  db:
    image: postgres:16.2
    container_name: book_game_db
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - db_network

  api:
    build: book_game_api
    container_name: book_game_api
    restart: always
    networks:
      - db_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  db_network:
